name: GitHub Actions Demo
on: [push]
jobs:
  build:
    name:  Build test
    runs-on: windows-latest
    steps:
    - uses: actions/checkout@v2
    - name: Setup .NET Core SDK ${{ matrix.dotnet-version }}
      uses: actions/setup-dotnet@v1.7.2
      with:
        dotnet-version: ${{ matrix.dotnet-version }}
    - name: Install dependencies
      run: dotnet restore
    - name: Build
      run: dotnet build --configuration Release --no-restore
      
  unittests:      
    needs: build
    name:  Unit Testing
    runs-on: windows-latest
    steps:
    - uses: actions/checkout@v2
    - name: Setup .NET Core SDK ${{ matrix.dotnet-version }}
      uses: actions/setup-dotnet@v1.7.2
      with:
        dotnet-version: ${{ matrix.dotnet-version }}
    - name: Install dependencies
      run: dotnet restore
    - name: Unit Tests
      run: dotnet test DetermineShippingCostsTest --no-restore --verbosity Minimal   
      
  soapuitest:      
    needs: build
    name:  SoapUI Testing
    runs-on: windows-latest
    steps:
    - uses: actions/checkout@v2
    - name: Setup .NET Core SDK ${{ matrix.dotnet-version }}
      uses: actions/setup-dotnet@v1.7.2
      with:
        dotnet-version: ${{ matrix.dotnet-version }}
    - name: Install dependencies
      run: dotnet restore
    - name: SoapUI Tests
      working-directory: ./SoapUI
      run: ./testrunner.bat "/Users/alexandertrappenberg/Sites/ShippingCosts/SoapUI/DemoWebshop-soapui-project.xml"
      
  neoload:      
    needs: build
    name:  NeoLoad Testing
    runs-on: windows-latest
    steps:
    - uses: actions/checkout@v2
    - name: Setup .NET Core SDK ${{ matrix.dotnet-version }}
      uses: actions/setup-dotnet@v1.7.2
      with:
        dotnet-version: ${{ matrix.dotnet-version }}
    - name: Install dependencies
      run: dotnet restore
    - name: NeoLoad Tests
      working-directory: ./NeoLoad
      run: ./AvansWebshopDemo.nlp -launch scenario1 -report
